#!/bin/bash

if [ $# -eq 0 ]; then
  printf "Usage:\n\nchefdeli [list of nodes]\n\n"
  exit 1
fi

if [ "$1" = "-h" -o "$1" = "--help" ];
then
  printf "\nCommand to delete Chef nodes and clients from the Chef host.\n\nusage:\n\n    chefdeli [list of hostnames]\n\n"
  exit 0
fi

NODES=$@

printf "\n777777777777777~,,,,,,,,~=+++?+++++=~~,,,.......??I?+=~~~~~~\n"
printf "777777777777777,,:,.,,,,~++???????+++=~..........~~~~=~~~~~~\n"
printf "777777777777I7::,,,:,.,~++?????????++==:...,.,...,=======~~~\n"
printf "77777777777?++,,,,,,,,,~++????????+?++=:....,,....~===~==~~~\n"
printf "777777777++?+,.,:,,:~,,:~~:=+????~::~=+::..,,.....~===~=~~~~\n"
printf "777777777?+?+:,,,,,.,::~+~~~=+???=~:,.:~~.........~===~==~~~\n"
printf "7777777I++?+~,.:,.,..:::,:,~~~+?+~:,:,.,~:.......,~~===+=~=~\n"
printf "7777777I++++,..,,....:~,:~,+~~+?==,:,=:~==.......,~=======~~\n"
printf "77777777I7II....,..,,,:++????++?==????++++~......,~==~~====~\n"
printf "77777777I+I+........,,~+????+++?+++????+==~.......~=~=~~=~~=\n"
printf "77777777II+:..........~+????+=+?+=+++?++=~:.......,=~~==~==~\n"
printf "77777777II=I:.......,.=++?++=====~~=+++==:,........~=~=~~=~=\n"
printf "77777777777:,.........~=+=+++++~=++++===~:,........,~~======\n"
printf "7777777IIII?,,........,~~=++++???+++====~:...........~==~~~~\n"
printf "777777777I7,.,........:=++=:~======:=++=~:..........,,=~~~~~\n"
printf "7777I7777?,,...,,.,,...:=++=~=+=+=~==++=~:...........,~=~~~~\n"
printf "77777777I,........,,,....=+===~~~~==++=~,.............~~~~~~\n"
printf "777777I?,................,=+++??+?++==~.~.~...........,~=~~~\n"
printf "7777I77+,.,,...............~=+??+++=~,.~:.,..........,~:=~~=\n"
printf "777777?,.,,.,,,....,,........,~~~~:,.:~~,.::.........:~~~~==\n"
printf "7777III,,,,,.,,.....,,~...........,::~~~..,+.......~~::~=~~~\n\n"

if [ $# -eq 0 ]; then
  printf "Usage:\n\nchefdeli [list of nodes]\n\n"
  exit 1
fi

printf "You're about to remove the node and client for...\n"
for arg; do
  printf "$arg\n"
done
printf "\nAre you Cher? Because you can't Turn Back Time... (Y/n) "

read x

if [ "$x" = "Y" ];
then

  printf "\n"

  for arg; do
    printf "Removing node and client for $arg...\n"
    yes | knife node delete $arg > /dev/null
    yes | knife client delete $arg > /dev/null
  done

  printf "\nSuccess: I Threw It All Away\n"

else

  printf "\nAborted: Our Day Will Come\n"

fi
exit 0
